#pragma once
genum_HTTP,
    genum_httpDoListen,
genum_GetBindPortsREQ,
genum_httpRequestIncoming,
     genum_GetBindPortsRSP,
     genum_WSTextMessage,
     genum_WSDisaccepted,
     genum_WSDisconnected,
    genum_WSWrite,
    // genum_WSConnected,
    genum_httpRequestStartChunking,
    genum_httpRequestChunkReceived,
    genum_httpRequestChunkingCompleted,
