/*
Found 172 symbols starting with @g_
  @g_AV -> 0xa211021e at ./mt/corelib/ifacesEvent.h:9
  @g_AddTxREQ -> 0x5d9cb4d0 at ./js/Event/bcEvent.h:26
  @g_AddTxRSP -> 0x2a79d245 at ./js/Event/bcEvent.h:27
  @g_BlockStreamer -> 0xf81ec75d at ./js/Event/bcEvent.h:19
  @g_BlockValidator -> 0xae2f87c8 at ./js/Event/bcEvent.h:15
  @g_BroadcastMessage -> 0x345115a3 at ./js/Event/bcEvent.h:36
  @g_BroadcasterTree -> 0x88a3eeef at ./js/Event/bcEvent.h:17
  @g_ClientTxSubscribeREQ -> 0x41eba206 at ./js/Event/bcEvent.h:32
  @g_ClientTxSubscribeRSP -> 0x722f21f at ./js/Event/bcEvent.h:33
  @g_DFSCaps -> 0x347aaa85 at ./mt/Events/DFS/capsEvent.h:12
  @g_DFSCaps_GetCloudRootsREQ -> 0x70568b38 at ./mt/Events/DFS/capsEvent.h:21
  @g_DFSCaps_GetCloudRootsRSP -> 0x3d835a8d at ./mt/Events/DFS/capsEvent.h:22
  @g_DFSCaps_GetReferrersREQ -> 0x254e2afe at ./mt/Events/DFS/capsEvent.h:19
  @g_DFSCaps_GetReferrersRSP -> 0x2a349af7 at ./mt/Events/DFS/capsEvent.h:20
  @g_DFSCaps_RegisterCloudRoot -> 0xfe5aade4 at ./mt/Events/DFS/capsEvent.h:18
  @g_DFSCaps_RegisterMyRefferrerNodeREQ -> 0xd778340c at ./mt/Events/DFS/capsEvent.h:17
  @g_DFSReferrer -> 0xe46c9617 at ./mt/Events/DFS/referrerEvent.h:12
  @g_DFSReferrerInitClient -> 0xf8c3c2ea at ./mt/Events/DFS/referrerEvent.h:33
  @g_DFSReferrerNotifyReferrerDownlinkDisconnected -> 0xfc5b6eb2 at ./mt/Events/DFS/referrerEvent.h:32
  @g_DFSReferrerNotifyReferrerUplinkIsConnected -> 0x76340fdb at ./mt/Events/DFS/referrerEvent.h:30
  @g_DFSReferrerNotifyReferrerUplinkIsDisconnected -> 0x139014af at ./mt/Events/DFS/referrerEvent.h:31
  @g_DFSReferrerUpdateConfigREQ -> 0x1a3f2508 at ./mt/Events/DFS/referrerEvent.h:35
  @g_DFSReferrerUpdateConfigRSP -> 0x671b78fd at ./mt/Events/DFS/referrerEvent.h:36
  @g_DFSReferrer_Hello -> 0x5a1bda40 at ./mt/Events/DFS/referrerEvent.h:20
  @g_DFSReferrer_Noop -> 0x1106c3e8 at ./mt/Events/DFS/referrerEvent.h:22
  @g_DFSReferrer_Ping -> 0x79e74f30 at ./mt/Events/DFS/referrerEvent.h:19
  @g_DFSReferrer_Pong -> 0xe7e44672 at ./mt/Events/DFS/referrerEvent.h:29
  @g_DFSReferrer_SubscribeNotifications -> 0x8f7f1f24 at ./mt/Events/DFS/referrerEvent.h:21
  @g_DFSReferrer_ToplinkDeliverREQ -> 0x406c473c at ./mt/Events/DFS/referrerEvent.h:24
  @g_DFSReferrer_ToplinkDeliverRSP -> 0x3d844769 at ./mt/Events/DFS/referrerEvent.h:25
  @g_EmitterData -> 0x2a113c9d at ./js/common/mtjsEvent.h:24
  @g_ErrorDispatcher -> 0xa7258eac at ./mt/Events/Tools/errorDispatcherEvent.h:15
  @g_ErrorRSP -> 0x846c69fa at ./mt/Events/System/Error/ErrorEvent.h:10
  @g_GEOIP -> 0x5ecb0003 at ./mt/corelib/ifacesEvent.h:11
  @g_GetBindPortsREQ -> 0x133ead50 at ./mt/Events/System/Net/httpEvent.h:15
  @g_GetBindPortsRSP -> 0xe01bcac5 at ./mt/Events/System/Net/httpEvent.h:16
  @g_GetGranulesREQ -> 0xe94cd5cc at ./js/Event/bcEvent.h:46
  @g_GetGranulesRSP -> 0x26171bd9 at ./js/Event/bcEvent.h:47
  @g_GetUserNonceREQ -> 0xf3c6da11 at ./js/Event/bcEvent.h:42
  @g_GetUserNonceRSP -> 0x2e8f89f8 at ./js/Event/bcEvent.h:43
  @g_GrainReader -> 0x8912dec7 at ./js/Event/bcEvent.h:18
  @g_GrainWriter -> 0xe14ad73b at ./js/Event/bcEvent.h:20
  @g_HTTP -> 0xf8f8e915 at ./mt/Events/System/Net/httpEvent.h:10
  @g_HeartBeatREQ -> 0x81966a5d at ./js/Event/bcEvent.h:40
  @g_InvalidateRoot -> 0xae09ed8 at ./js/Event/bcEvent.h:35
  @g_JsonREQ -> 0x689b16c9 at ./mt/Events/System/Net/jsonRefEvent.h:11
  @g_JsonRSP -> 0x23649030 at ./mt/Events/System/Net/jsonRefEvent.h:13
  @g_LeaderElection -> 0x56ff505b at ./js/Event/bcEvent.h:21
  @g_Logger -> 0x58fe27c5 at ./mt/Events/Tools/loggerEvent.h:16
  @g_Mysql -> 0x1eb55b6d at ./mt/corelib/DBHEvent.h:6
  @g_Node -> 0x68e6b4fd at ./js/Event/bcEvent.h:14
  @g_NodeMsgREQ -> 0x2c9faa42 at ./js/Event/bcEvent.h:28
  @g_NodeMsgRSP -> 0xe1721493 at ./js/Event/bcEvent.h:29
  @g_ObjectProxyPolled -> 0x30489b56 at ./mt/Events/System/Net/rpcEvent.h:13
  @g_ObjectProxyThreaded -> 0x835c46b3 at ./mt/Events/System/Net/rpcEvent.h:14
  @g_Oscar -> 0x5795b27f at ./mt/Events/System/Net/oscarEvent.h:12
  @g_OscarSecure -> 0x86d21df6 at ./mt/Events/System/Net/oscarEvent.h:13
  @g_Postgres -> 0xaf73ca5e at ./mt/corelib/DBHEvent.h:7
  @g_PutTransactionREQ -> 0x8f837012 at ./js/Event/bcEvent.h:41
  @g_RPC -> 0xd7a04764 at ./mt/Events/System/Net/rpcEvent.h:12
  @g_RefferrerClient -> 0xec5a94b7 at ./mt/Events/DFS/referrerEvent.h:13
  @g_SSL -> 0xc02aafad at ./mt/corelib/ifacesEvent.h:10
  @g_SendToChild -> 0xa6491fa0 at ./js/Event/bcEvent.h:37
  @g_SendToChildAck -> 0xf4240201 at ./js/Event/bcEvent.h:38
  @g_ServiceInit -> 0x6c13a296 at ./js/Event/bcEvent.h:34
  @g_Socket -> 0x766cd5dc at ./mt/Events/System/Net/socketEvent.h:13
  @g_Socks5 -> 0xbba35c75 at ./mt/Events/System/Net/socketEvent.h:14
  @g_StreamBlock -> 0x292ad1d2 at ./js/Event/bcEvent.h:39
  @g_Telnet -> 0xd7fc786d at ./mt/Events/Tools/telnetEvent.h:10
  @g_Timer -> 0x624ad572 at ./mt/Events/System/timerEvent.h:9
  @g_TxValidator -> 0x9eb9ef5d at ./js/Event/bcEvent.h:16
  @g_WSDisaccepted -> 0xae69496c at ./mt/Events/System/Net/httpEvent.h:18
  @g_WSDisconnected -> 0xa435c09c at ./mt/Events/System/Net/httpEvent.h:19
  @g_WSTextMessage -> 0x8cc926af at ./mt/Events/System/Net/httpEvent.h:17
  @g_WSWrite -> 0xd99e86f2 at ./mt/Events/System/Net/httpEvent.h:20
  @g_WebHandler -> 0xf8eb4187 at ./mt/Events/Tools/webHandlerEvent.h:14
  @g_WebSocketClient -> 0xe043d1cf at ./mt/Events/System/Net/webSocketClientEvent.h:6
  @g_WriteBlock -> 0x95431445 at ./js/Event/bcEvent.h:45
  @g_WriteGranules -> 0x42352db at ./js/Event/bcEvent.h:44
  @g_bcClientMsg -> 0x66eb46e6 at ./js/Event/bcEvent.h:30
  @g_bcClientMsgReply -> 0xf5a8f29a at ./js/Event/bcEvent.h:31
  @g_errorDispatcherNotifySubscriber -> 0x4f809243 at ./mt/Events/Tools/errorDispatcherEvent.h:23
  @g_errorDispatcherSendMessage -> 0xf855f5d9 at ./mt/Events/Tools/errorDispatcherEvent.h:20
  @g_errorDispatcherSubscribe -> 0xc556104c at ./mt/Events/Tools/errorDispatcherEvent.h:21
  @g_errorDispatcherUnsubscribe -> 0xbf4a16f1 at ./mt/Events/Tools/errorDispatcherEvent.h:22
  @g_httpDoListen -> 0x3d92a37f at ./mt/Events/System/Net/httpEvent.h:14
  @g_httpRequestChunkReceived -> 0x8bdf4988 at ./mt/Events/System/Net/httpEvent.h:24
  @g_httpRequestChunkingCompleted -> 0x298b445e at ./mt/Events/System/Net/httpEvent.h:25
  @g_httpRequestIncoming -> 0x3d15919a at ./mt/Events/System/Net/httpEvent.h:22
  @g_httpRequestStartChunking -> 0x3d17e099 at ./mt/Events/System/Net/httpEvent.h:23
  @g_loggerLogMessage -> 0x78ff5a08 at ./mt/Events/Tools/loggerEvent.h:21
  @g_mtjs -> 0x49fcd94b at ./js/common/mtjsEvent.h:14
  @g_mtjsRpcREQ -> 0xdf150a4e at ./js/common/mtjsEvent.h:25
  @g_mtjsRpcRSP -> 0xa44c5a67 at ./js/common/mtjsEvent.h:26
  @g_mtjs_Eval -> 0x46ca4e8a at ./js/common/mtjsEvent.h:23
  @g_mtjs_async_executed -> 0xe8f5f20c at ./js/common/mtjsEvent.h:22
  @g_oscar_Accepted -> 0x3e0c01b9 at ./mt/Events/System/Net/oscarEvent.h:26
  @g_oscar_AddToListenTCP -> 0x54613024 at ./mt/Events/System/Net/oscarEvent.h:20
  @g_oscar_Connect -> 0xa5e6d3b6 at ./mt/Events/System/Net/oscarEvent.h:21
  @g_oscar_ConnectFailed -> 0x83821357 at ./mt/Events/System/Net/oscarEvent.h:30
  @g_oscar_Connected -> 0x2a45a837 at ./mt/Events/System/Net/oscarEvent.h:24
  @g_oscar_Disaccepted -> 0xb934e4cd at ./mt/Events/System/Net/oscarEvent.h:27
  @g_oscar_Disconnected -> 0x938c352b at ./mt/Events/System/Net/oscarEvent.h:25
  @g_oscar_NotifyBindAddress -> 0x81c4836a at ./mt/Events/System/Net/oscarEvent.h:28
  @g_oscar_NotifyOutBufferEmpty -> 0xf774d3b2 at ./mt/Events/System/Net/oscarEvent.h:29
  @g_oscar_PacketOnAcceptor -> 0xb9821244 at ./mt/Events/System/Net/oscarEvent.h:22
  @g_oscar_PacketOnConnector -> 0x78cd6494 at ./mt/Events/System/Net/oscarEvent.h:23
  @g_oscar_SendPacket -> 0x604e1706 at ./mt/Events/System/Net/oscarEvent.h:19
  @g_prodtestServer -> 0x1ce123eb at ./mt/test/test_http_rpc/Events/___prodtestEvent.h:8
  @g_prodtestServerWeb -> 0xafe45ff3 at ./mt/test/test_http_rpc/Events/___prodtestEvent.h:9
  @g_pt_AddTaskREQ -> 0x69952388 at ./mt/test/test_http_rpc/Events/___prodtestEvent.h:15
  @g_pt_AddTaskRSP -> 0xb671777d at ./mt/test/test_http_rpc/Events/___prodtestEvent.h:16
  @g_rpcAccepted -> 0x4fe5930d at ./mt/Events/System/Net/rpcEvent.h:29
  @g_rpcBinded -> 0x4504665a at ./mt/Events/System/Net/rpcEvent.h:30
  @g_rpcConnectFailed -> 0x841e7a0b at ./mt/Events/System/Net/rpcEvent.h:27
  @g_rpcConnected -> 0xe890e6b at ./mt/Events/System/Net/rpcEvent.h:28
  @g_rpcDisaccepted -> 0x1848be01 at ./mt/Events/System/Net/rpcEvent.h:26
  @g_rpcDisconnected -> 0x16d10dff at ./mt/Events/System/Net/rpcEvent.h:25
  @g_rpcIncomingOnAcceptor -> 0xff36ca0c at ./mt/Events/System/Net/rpcEvent.h:31
  @g_rpcIncomingOnConnector -> 0x7dfa185c at ./mt/Events/System/Net/rpcEvent.h:32
  @g_rpcPassPacket -> 0xf683c539 at ./mt/Events/System/Net/rpcEvent.h:21
  @g_rpcSendPacket -> 0x2dbb6362 at ./mt/Events/System/Net/rpcEvent.h:22
  @g_rpcSubscribeNotifications -> 0xfa923d98 at ./mt/Events/System/Net/rpcEvent.h:23
  @g_rpcTest -> 0xf2130640 at ./mt/test/rpc/testRpcEvent.h:11
  @g_rpcTestService1 -> 0x36d02066 at ./mt/test/rpc/testRpcEvent.h:12
  @g_rpcTestService2 -> 0x35d01ed3 at ./mt/test/rpc/testRpcEvent.h:13
  @g_rpcUnsubscribeNotifications -> 0x4bdcaeb3 at ./mt/Events/System/Net/rpcEvent.h:24
  @g_rpc_DoListen -> 0xc40566ab at ./mt/Events/System/Net/rpcEvent.h:34
  @g_rpc_NotifyOutBufferEmpty -> 0xba31a8cb at ./mt/Events/System/Net/rpcEvent.h:33
  @g_socket_Accepted -> 0xb78286e4 at ./mt/Events/System/Net/socketEvent.h:22
  @g_socket_AddToConnectTCP -> 0x8d1480d8 at ./mt/Events/System/Net/socketEvent.h:21
  @g_socket_AddToListenTCP -> 0xd67c2f01 at ./mt/Events/System/Net/socketEvent.h:20
  @g_socket_ConnectFailed -> 0x3f06d37c at ./mt/Events/System/Net/socketEvent.h:29
  @g_socket_Connected -> 0x4137de94 at ./mt/Events/System/Net/socketEvent.h:24
  @g_socket_Disaccepted -> 0x68a6459e at ./mt/Events/System/Net/socketEvent.h:26
  @g_socket_Disconnected -> 0x136d460e at ./mt/Events/System/Net/socketEvent.h:25
  @g_socket_NotifyBindAddress -> 0x70f58e5 at ./mt/Events/System/Net/socketEvent.h:27
  @g_socket_NotifyOutBufferEmpty -> 0x8e284013 at ./mt/Events/System/Net/socketEvent.h:28
  @g_socket_StreamRead -> 0x91827a21 at ./mt/Events/System/Net/socketEvent.h:23
  @g_socket_UdpAssoc -> 0x912178b3 at ./mt/Events/System/Net/socketEvent.h:30
  @g_socket_UdpAssocRSP -> 0x2e9bf50 at ./mt/Events/System/Net/socketEvent.h:31
  @g_socket_UdpPacketIncoming -> 0x3c84a0bc at ./mt/Events/System/Net/socketEvent.h:32
  @g_socket_Write -> 0xf12fb6c0 at ./mt/Events/System/Net/socketEvent.h:33
  @g_startService -> 0xeb05e092 at ./mt/Events/System/Run/startServiceEvent.h:9
  @g_teldemo1 -> 0xb8351714 at ./mt/test/telnet/Events/___teldemoEvent.h:8
  @g_teldemo2 -> 0xbb351bcd at ./mt/test/telnet/Events/___teldemoEvent.h:9
  @g_telnetCommandEntered -> 0x849d764d at ./mt/Events/Tools/telnetEvent.h:25
  @g_telnetDoListen -> 0x625d9177 at ./mt/Events/Tools/telnetEvent.h:24
  @g_telnetRegisterCommand -> 0x86bc4951 at ./mt/Events/Tools/telnetEvent.h:22
  @g_telnetReply -> 0xfc078aff at ./mt/Events/Tools/telnetEvent.h:23
  @g_testREQ -> 0x46cb0bc3 at ./mt/test/rpc/testRpcEvent.h:16
  @g_testRSP -> 0x8a018f36 at ./mt/test/rpc/testRpcEvent.h:17
  @g_testTimer -> 0xa8c3d0f2 at ./mt/test/timer/___testEvent.h:10
  @g_testWSC -> 0x707bc584 at ./mt/test/test_ws/___testEvent2.h:8
  @g_testWebServer -> 0xf971d8e6 at ./mt/test/test_http/___testEvent.h:7
  @g_testWebServer2 -> 0x823855bc at ./mt/test/test_ws/___testEvent2.h:7
  @g_timerResetAlarm -> 0x684f5e1a at ./mt/Events/System/timerEvent.h:16
  @g_timerSetAlarm -> 0x6922dbff at ./mt/Events/System/timerEvent.h:15
  @g_timerSetTimer -> 0x42db2123 at ./mt/Events/System/timerEvent.h:14
  @g_timerStopAlarm -> 0x398e5577 at ./mt/Events/System/timerEvent.h:18
  @g_timerStopTimer -> 0xa95f69fb at ./mt/Events/System/timerEvent.h:17
  @g_timerTickAlarm -> 0x1d9c387c at ./mt/Events/System/timerEvent.h:20
  @g_timerTickTimer -> 0xedcab8fc at ./mt/Events/System/timerEvent.h:19
  @g_webHandlerRegisterDirectory -> 0xf474cb49 at ./mt/Events/Tools/webHandlerEvent.h:21
  @g_webHandlerRegisterHandler -> 0x32b92c72 at ./mt/Events/Tools/webHandlerEvent.h:20
  @g_webHandlerRequestIncoming -> 0x7562f28c at ./mt/Events/Tools/webHandlerEvent.h:22
  @g_wscConnect -> 0x5f2db73a at ./mt/Events/System/Net/webSocketClientEvent.h:13
  @g_wscConnectFailed -> 0xa119ee2b at ./mt/Events/System/Net/webSocketClientEvent.h:19
  @g_wscConnected -> 0xb7e20ccb at ./mt/Events/System/Net/webSocketClientEvent.h:14
  @g_wscDisconnected -> 0x3e4d18df at ./mt/Events/System/Net/webSocketClientEvent.h:15
  @g_wscReceived -> 0x72d44007 at ./mt/Events/System/Net/webSocketClientEvent.h:17
  @g_wscSend -> 0xfa9c0e1a at ./mt/Events/System/Net/webSocketClientEvent.h:16
*/

/// === GENERATED CODE ===
#include <stdint.h>
#include "ghash.h"
// Auto-generated switch case with hashes
const char* get_symbol_name(uint32_t hash) {
    switch (hash) {
        case ghash("@g_AV") : return "AV";
        case ghash("@g_AddTxREQ") : return "AddTxREQ";
        case ghash("@g_AddTxRSP") : return "AddTxRSP";
        case ghash("@g_BlockStreamer") : return "BlockStreamer";
        case ghash("@g_BlockValidator") : return "BlockValidator";
        case ghash("@g_BroadcastMessage") : return "BroadcastMessage";
        case ghash("@g_BroadcasterTree") : return "BroadcasterTree";
        case ghash("@g_ClientTxSubscribeREQ") : return "ClientTxSubscribeREQ";
        case ghash("@g_ClientTxSubscribeRSP") : return "ClientTxSubscribeRSP";
        case ghash("@g_DFSCaps") : return "DFSCaps";
        case ghash("@g_DFSCaps_GetCloudRootsREQ") : return "DFSCaps_GetCloudRootsREQ";
        case ghash("@g_DFSCaps_GetCloudRootsRSP") : return "DFSCaps_GetCloudRootsRSP";
        case ghash("@g_DFSCaps_GetReferrersREQ") : return "DFSCaps_GetReferrersREQ";
        case ghash("@g_DFSCaps_GetReferrersRSP") : return "DFSCaps_GetReferrersRSP";
        case ghash("@g_DFSCaps_RegisterCloudRoot") : return "DFSCaps_RegisterCloudRoot";
        case ghash("@g_DFSCaps_RegisterMyRefferrerNodeREQ") : return "DFSCaps_RegisterMyRefferrerNodeREQ";
        case ghash("@g_DFSReferrer") : return "DFSReferrer";
        case ghash("@g_DFSReferrerInitClient") : return "DFSReferrerInitClient";
        case ghash("@g_DFSReferrerNotifyReferrerDownlinkDisconnected") : return "DFSReferrerNotifyReferrerDownlinkDisconnected";
        case ghash("@g_DFSReferrerNotifyReferrerUplinkIsConnected") : return "DFSReferrerNotifyReferrerUplinkIsConnected";
        case ghash("@g_DFSReferrerNotifyReferrerUplinkIsDisconnected") : return "DFSReferrerNotifyReferrerUplinkIsDisconnected";
        case ghash("@g_DFSReferrerUpdateConfigREQ") : return "DFSReferrerUpdateConfigREQ";
        case ghash("@g_DFSReferrerUpdateConfigRSP") : return "DFSReferrerUpdateConfigRSP";
        case ghash("@g_DFSReferrer_Hello") : return "DFSReferrer_Hello";
        case ghash("@g_DFSReferrer_Noop") : return "DFSReferrer_Noop";
        case ghash("@g_DFSReferrer_Ping") : return "DFSReferrer_Ping";
        case ghash("@g_DFSReferrer_Pong") : return "DFSReferrer_Pong";
        case ghash("@g_DFSReferrer_SubscribeNotifications") : return "DFSReferrer_SubscribeNotifications";
        case ghash("@g_DFSReferrer_ToplinkDeliverREQ") : return "DFSReferrer_ToplinkDeliverREQ";
        case ghash("@g_DFSReferrer_ToplinkDeliverRSP") : return "DFSReferrer_ToplinkDeliverRSP";
        case ghash("@g_EmitterData") : return "EmitterData";
        case ghash("@g_ErrorDispatcher") : return "ErrorDispatcher";
        case ghash("@g_ErrorRSP") : return "ErrorRSP";
        case ghash("@g_GEOIP") : return "GEOIP";
        case ghash("@g_GetBindPortsREQ") : return "GetBindPortsREQ";
        case ghash("@g_GetBindPortsRSP") : return "GetBindPortsRSP";
        case ghash("@g_GetGranulesREQ") : return "GetGranulesREQ";
        case ghash("@g_GetGranulesRSP") : return "GetGranulesRSP";
        case ghash("@g_GetUserNonceREQ") : return "GetUserNonceREQ";
        case ghash("@g_GetUserNonceRSP") : return "GetUserNonceRSP";
        case ghash("@g_GrainReader") : return "GrainReader";
        case ghash("@g_GrainWriter") : return "GrainWriter";
        case ghash("@g_HTTP") : return "HTTP";
        case ghash("@g_HeartBeatREQ") : return "HeartBeatREQ";
        case ghash("@g_InvalidateRoot") : return "InvalidateRoot";
        case ghash("@g_JsonREQ") : return "JsonREQ";
        case ghash("@g_JsonRSP") : return "JsonRSP";
        case ghash("@g_LeaderElection") : return "LeaderElection";
        case ghash("@g_Logger") : return "Logger";
        case ghash("@g_Mysql") : return "Mysql";
        case ghash("@g_Node") : return "Node";
        case ghash("@g_NodeMsgREQ") : return "NodeMsgREQ";
        case ghash("@g_NodeMsgRSP") : return "NodeMsgRSP";
        case ghash("@g_ObjectProxyPolled") : return "ObjectProxyPolled";
        case ghash("@g_ObjectProxyThreaded") : return "ObjectProxyThreaded";
        case ghash("@g_Oscar") : return "Oscar";
        case ghash("@g_OscarSecure") : return "OscarSecure";
        case ghash("@g_Postgres") : return "Postgres";
        case ghash("@g_PutTransactionREQ") : return "PutTransactionREQ";
        case ghash("@g_RPC") : return "RPC";
        case ghash("@g_RefferrerClient") : return "RefferrerClient";
        case ghash("@g_SSL") : return "SSL";
        case ghash("@g_SendToChild") : return "SendToChild";
        case ghash("@g_SendToChildAck") : return "SendToChildAck";
        case ghash("@g_ServiceInit") : return "ServiceInit";
        case ghash("@g_Socket") : return "Socket";
        case ghash("@g_Socks5") : return "Socks5";
        case ghash("@g_StreamBlock") : return "StreamBlock";
        case ghash("@g_Telnet") : return "Telnet";
        case ghash("@g_Timer") : return "Timer";
        case ghash("@g_TxValidator") : return "TxValidator";
        case ghash("@g_WSDisaccepted") : return "WSDisaccepted";
        case ghash("@g_WSDisconnected") : return "WSDisconnected";
        case ghash("@g_WSTextMessage") : return "WSTextMessage";
        case ghash("@g_WSWrite") : return "WSWrite";
        case ghash("@g_WebHandler") : return "WebHandler";
        case ghash("@g_WebSocketClient") : return "WebSocketClient";
        case ghash("@g_WriteBlock") : return "WriteBlock";
        case ghash("@g_WriteGranules") : return "WriteGranules";
        case ghash("@g_bcClientMsg") : return "bcClientMsg";
        case ghash("@g_bcClientMsgReply") : return "bcClientMsgReply";
        case ghash("@g_errorDispatcherNotifySubscriber") : return "errorDispatcherNotifySubscriber";
        case ghash("@g_errorDispatcherSendMessage") : return "errorDispatcherSendMessage";
        case ghash("@g_errorDispatcherSubscribe") : return "errorDispatcherSubscribe";
        case ghash("@g_errorDispatcherUnsubscribe") : return "errorDispatcherUnsubscribe";
        case ghash("@g_httpDoListen") : return "httpDoListen";
        case ghash("@g_httpRequestChunkReceived") : return "httpRequestChunkReceived";
        case ghash("@g_httpRequestChunkingCompleted") : return "httpRequestChunkingCompleted";
        case ghash("@g_httpRequestIncoming") : return "httpRequestIncoming";
        case ghash("@g_httpRequestStartChunking") : return "httpRequestStartChunking";
        case ghash("@g_loggerLogMessage") : return "loggerLogMessage";
        case ghash("@g_mtjs") : return "mtjs";
        case ghash("@g_mtjsRpcREQ") : return "mtjsRpcREQ";
        case ghash("@g_mtjsRpcRSP") : return "mtjsRpcRSP";
        case ghash("@g_mtjs_Eval") : return "mtjs_Eval";
        case ghash("@g_mtjs_async_executed") : return "mtjs_async_executed";
        case ghash("@g_oscar_Accepted") : return "oscar_Accepted";
        case ghash("@g_oscar_AddToListenTCP") : return "oscar_AddToListenTCP";
        case ghash("@g_oscar_Connect") : return "oscar_Connect";
        case ghash("@g_oscar_ConnectFailed") : return "oscar_ConnectFailed";
        case ghash("@g_oscar_Connected") : return "oscar_Connected";
        case ghash("@g_oscar_Disaccepted") : return "oscar_Disaccepted";
        case ghash("@g_oscar_Disconnected") : return "oscar_Disconnected";
        case ghash("@g_oscar_NotifyBindAddress") : return "oscar_NotifyBindAddress";
        case ghash("@g_oscar_NotifyOutBufferEmpty") : return "oscar_NotifyOutBufferEmpty";
        case ghash("@g_oscar_PacketOnAcceptor") : return "oscar_PacketOnAcceptor";
        case ghash("@g_oscar_PacketOnConnector") : return "oscar_PacketOnConnector";
        case ghash("@g_oscar_SendPacket") : return "oscar_SendPacket";
        case ghash("@g_prodtestServer") : return "prodtestServer";
        case ghash("@g_prodtestServerWeb") : return "prodtestServerWeb";
        case ghash("@g_pt_AddTaskREQ") : return "pt_AddTaskREQ";
        case ghash("@g_pt_AddTaskRSP") : return "pt_AddTaskRSP";
        case ghash("@g_rpcAccepted") : return "rpcAccepted";
        case ghash("@g_rpcBinded") : return "rpcBinded";
        case ghash("@g_rpcConnectFailed") : return "rpcConnectFailed";
        case ghash("@g_rpcConnected") : return "rpcConnected";
        case ghash("@g_rpcDisaccepted") : return "rpcDisaccepted";
        case ghash("@g_rpcDisconnected") : return "rpcDisconnected";
        case ghash("@g_rpcIncomingOnAcceptor") : return "rpcIncomingOnAcceptor";
        case ghash("@g_rpcIncomingOnConnector") : return "rpcIncomingOnConnector";
        case ghash("@g_rpcPassPacket") : return "rpcPassPacket";
        case ghash("@g_rpcSendPacket") : return "rpcSendPacket";
        case ghash("@g_rpcSubscribeNotifications") : return "rpcSubscribeNotifications";
        case ghash("@g_rpcTest") : return "rpcTest";
        case ghash("@g_rpcTestService1") : return "rpcTestService1";
        case ghash("@g_rpcTestService2") : return "rpcTestService2";
        case ghash("@g_rpcUnsubscribeNotifications") : return "rpcUnsubscribeNotifications";
        case ghash("@g_rpc_DoListen") : return "rpc_DoListen";
        case ghash("@g_rpc_NotifyOutBufferEmpty") : return "rpc_NotifyOutBufferEmpty";
        case ghash("@g_socket_Accepted") : return "socket_Accepted";
        case ghash("@g_socket_AddToConnectTCP") : return "socket_AddToConnectTCP";
        case ghash("@g_socket_AddToListenTCP") : return "socket_AddToListenTCP";
        case ghash("@g_socket_ConnectFailed") : return "socket_ConnectFailed";
        case ghash("@g_socket_Connected") : return "socket_Connected";
        case ghash("@g_socket_Disaccepted") : return "socket_Disaccepted";
        case ghash("@g_socket_Disconnected") : return "socket_Disconnected";
        case ghash("@g_socket_NotifyBindAddress") : return "socket_NotifyBindAddress";
        case ghash("@g_socket_NotifyOutBufferEmpty") : return "socket_NotifyOutBufferEmpty";
        case ghash("@g_socket_StreamRead") : return "socket_StreamRead";
        case ghash("@g_socket_UdpAssoc") : return "socket_UdpAssoc";
        case ghash("@g_socket_UdpAssocRSP") : return "socket_UdpAssocRSP";
        case ghash("@g_socket_UdpPacketIncoming") : return "socket_UdpPacketIncoming";
        case ghash("@g_socket_Write") : return "socket_Write";
        case ghash("@g_startService") : return "startService";
        case ghash("@g_teldemo1") : return "teldemo1";
        case ghash("@g_teldemo2") : return "teldemo2";
        case ghash("@g_telnetCommandEntered") : return "telnetCommandEntered";
        case ghash("@g_telnetDoListen") : return "telnetDoListen";
        case ghash("@g_telnetRegisterCommand") : return "telnetRegisterCommand";
        case ghash("@g_telnetReply") : return "telnetReply";
        case ghash("@g_testREQ") : return "testREQ";
        case ghash("@g_testRSP") : return "testRSP";
        case ghash("@g_testTimer") : return "testTimer";
        case ghash("@g_testWSC") : return "testWSC";
        case ghash("@g_testWebServer") : return "testWebServer";
        case ghash("@g_testWebServer2") : return "testWebServer2";
        case ghash("@g_timerResetAlarm") : return "timerResetAlarm";
        case ghash("@g_timerSetAlarm") : return "timerSetAlarm";
        case ghash("@g_timerSetTimer") : return "timerSetTimer";
        case ghash("@g_timerStopAlarm") : return "timerStopAlarm";
        case ghash("@g_timerStopTimer") : return "timerStopTimer";
        case ghash("@g_timerTickAlarm") : return "timerTickAlarm";
        case ghash("@g_timerTickTimer") : return "timerTickTimer";
        case ghash("@g_webHandlerRegisterDirectory") : return "webHandlerRegisterDirectory";
        case ghash("@g_webHandlerRegisterHandler") : return "webHandlerRegisterHandler";
        case ghash("@g_webHandlerRequestIncoming") : return "webHandlerRequestIncoming";
        case ghash("@g_wscConnect") : return "wscConnect";
        case ghash("@g_wscConnectFailed") : return "wscConnectFailed";
        case ghash("@g_wscConnected") : return "wscConnected";
        case ghash("@g_wscDisconnected") : return "wscDisconnected";
        case ghash("@g_wscReceived") : return "wscReceived";
        case ghash("@g_wscSend") : return "wscSend";
        default: return "unknown";
    }
}

