#pragma once

#define QUORUM 0.6777
#define SNAPSHOT_BLOCKS 1000
#define HOT_STORE_SIZE 30000

#define _1sec 1000000
// #define VALGRIND 1
#ifdef VALGRIND
#define MAX_INACTIVE_TIME 10.
#define BROADCAST_ACK_TIMEDOUT_SEC 2.
#define CONFIRM_LEADER_SENT_TIMEFRAME 10.
#define HEART_BEAT_SENT_TIMEFRAME 10.
#define VALIDATE_BLOCK_DELAY_set_TIMEFRAME 10.
#define BLOCK_ACCEPTED_SENT_TIMEFRAME 10.
#else

#define MAX_INACTIVE_TIME 3.
#define BROADCAST_ACK_TIMEDOUT_SEC 0.2
#define CONFIRM_LEADER_SENT_TIMEFRAME 1.
#define HEART_BEAT_SENT_TIMEFRAME 1.
#define VALIDATE_BLOCK_DELAY_set_TIMEFRAME 1.
#define BLOCK_ACCEPTED_SENT_TIMEFRAME 1.
#endif

