#pragma once

#define QUORUM 67 /* %% */
// #define SNAPSHOT_BLOCKS 1000
#define HOT_STORE_SIZE 30000

#define _1sec 1000000

#define HEART_BEAT_SENT_TIMEOUT 1
#define CONFIRM_LEADER_SENT_TIMEOUT 1
#define STAGE_IS_WORKING_TIMEOUT 2